name: CI + build only (fout)

on:
  pull_request:
    branches:
      - feature/break-test

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      #1. Haal de code op
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. PHP instellen
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 81
          tools: composer
          coverage: none

      # 3. Dependencies installeren
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # 4. Tests draaien (CI) + output naar bestand
      - name: Run tests
        run: |
          mkdir -p test-results
          composer test -- --log-junit test-results/junit.xml

      # 5. Upload testresultaten als artifact
      - name: Upload test results
        if: always()
        #ook uploaden als tests falen
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results